# Generated by Django 5.1.1 on 2024-10-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autentication', '0005_alter_enrollment_price_alter_membershipplan_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='DOB',
            field=models.DateField(),
        ),
    ]
